version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: fitness-app-jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - jenkins-network

  jenkins-agent:
    image: jenkins/inbound-agent
    container_name: jenkins-agent
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    depends_on:
      - jenkins
    networks:
      - jenkins-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:

networks:
  jenkins-network:
    driver: bridge